debug: False
gpu_id: ???
random_seed: ???
n_clients: ???
save_path: ???
result_path: ???
print_config: False


dataset:
  name: ???
  partition: ???
  n_nodes: ???
  n_features: ???
  n_clusters: ???
  ratio_train: ???
  ratio_test: ???

model:
  name: 'dmon'
  n_rounds: 100
  n_epochs_per_round: 25
  print_module_params: False

  learning_rate: ???
  weight_decay: ???
  architecture_size: ???
  cluster_size_regularization: ???
  orthogonality_regularization: ???
  dropout_rate: ???
